### ISSUE TITLE
Breaks inside `flex` column

### ISSUE THREAD

**Issue by atomiks** [pawelgrzybek/siema#156]
https://codepen.io/anon/pen/aYaKgg

Also when resizing, it goes crazy and the width goes to thousands of pixels

**Comment by pawelgrzybek** [comment]
Hi.

Nice spot. Siema doesn't apply fixed width to the container and assumes that the container is always full width (`100%`). Because of the way how width of flex items is calculated, this is technically correct behaviour. I will fix it in next release by applying a fixed width on a container. For now the easiest fix would be:

```css
.flex {
  display: flex;
}

.flex__left {
  flex: 2;
  overflow: hidden;
}

.flex__right {
  flex: 1;
}
```

It won't be needed in a next version of Siema.

Thanks for reporting and have a lovely day 👋
