### ISSUE TITLE
Newbie: How to make a fade instead of translate?

### ISSUE THREAD

**Issue by nickelmichel** [pawelgrzybek/siema#229]
Hi!
I know my question is silly but i'm not a developer, i only do some html/css and copy/past javascript most of the time!

I would like to make a fade transition instead of translation, how to?

Thanks a lot!

**Comment by eballeste** [comment]
thank you for not implementing fade, it forced me to think of alternative ways to implement without requiring a library to do it

**Comment by Zontir** [comment]
> thank you for not implementing fade, it forced me to think of alternative ways to implement without requiring a library to do it

Could you share how you did it? I would like to make this effect.

**Comment by eballeste** [comment]
```javascript
...
onChange: () => {
  const index = imageSlider.currentSlide

  // captions
  $captions.removeClass('active')
  $captions.eq(index).addClass('active')
}
...
```

captions are stacked on top of each other using css grids and hidden by default with opacity 0, the active class changes the opacity to 1

```html
<div class="captions>
  <div class="caption">1</div>
  <div class="caption">2</div>
  <div class="caption">...</div>
</div>
```

```scss
&__captions {
  display: grid;
  grid-template-columns: 1fr;
}

&__caption {
  transition: opacity .2s ease-in-out;
  opacity: 0;
  grid-row-start: 1;
  grid-column-start: 1;

  &.active {
    opacity: 1;
  }
}
```
